### ISSUE TITLE
Remove ui pod from auto deploy

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-gitops-ocp-turbonomic#18]
Need to remove automatically enabling ui deployment. Not needed with latest iteration as web ui is used.

**Comment by seansund** [comment]
@tcskill Is this issue still valid? Also, is the issue that the UI should be conditionally installed or is it a technical issue with the way we currently configure the instance?

**Comment by tcskill** [comment]
@seansund adding this as an optional probe

**Comment by tcskill** [comment]
closed with #20
