### ISSUE TITLE
Valdiate Destroy Stuck - Issues

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-ocp-turbonomic#24]
Trying to validate the build working before i apply changes for automation workflow build status clean. 

Validate destroy step seems to be stuck.

Build workflow : 
https://github.com/cloud-native-toolkit/terraform-gitops-ocp-turbonomic/runs/6379576256?check_suite_focus=true

**Comment by tcskill** [comment]
@balasgit there's something with the way the argo apps created are hanging I've noticed, something changed in argo that is adding finalizers that were never there before.  I'll make the change to the destroy script.

**Comment by balasgit** [comment]
Thanks @tcskill for quick response and appreciated to fix this issues. thanks

**Comment by tcskill** [comment]
closing - stale issue that has been addressed by recent releases
