### ISSUE TITLE
IBM'er Turbonomic license access instructions needs update.

### ISSUE THREAD

**Issue by dbennerIBM** [cloud-native-toolkit/terraform-gitops-ocp-turbonomic#26]
License file in package M05C4EN IBM Turbonomic Application Resource Management On-Prem 8.4.6 for install on Kubernetes English is expired. After downloading the 11GB package I discovered that the license contained in the package was expired in July 2022 as the name of the file implies, CP4MCM_IBM_ARM_OEM_Premier_License_July_2022.lic

Is there a more up to date package available?

**Comment by dbennerIBM** [comment]
A potential fix is to include reaching out via Slack to @Shivo to get a 30 day enablement license. Be sure to say "enablement" because he won't give you one for a customer facing demo.

**Comment by travistolle** [comment]
Tom, I investigated and indeed this updated package, M07FSEN, contains a valid license.  Here are the revised lines that should fix the issue with the documentation on the  solution [Turbonomic solution ](https://builder.techzone-automation.com/solutions/turbonomic-multicloud) page: 

3. Select the package M07FSEN Turbonomic Application Resource Management On-Prem 8.6 for install on Kubernetes English and download, this file is 12gb in size, once downloaded unzip to find the license key
4. Extract this download package to get the turbonomic license key This package contains license file for turbonomic, with a name similar to “TURBONOMIC-ARM.lic"

**Comment by dbennerIBM** [comment]
Tom, I investigated and indeed this updated package, M07FSEN, contains a valid license. Here are the revised lines that should fix the issue with the documentation on the solution [Turbonomic solution ](https://builder.techzone-automation.com/solutions/turbonomic-multicloud)page:

3. Select the package M07FSEN Turbonomic Application Resource Management On-Prem 8.6 for install on Kubernetes English and download, this file is 12gb in size, once downloaded unzip to find the license key

4. Extract this download package to get the turbonomic license key This package contains license file for turbonomic, with a name similar to “TURBONOMIC-ARM.lic"

Best, 
Daniel

**Comment by tcskill** [comment]
this has been updated in the bom readme to reflect the change.
